[package]
name = "auto_install_for_Win7"
version = "0.1.0"
authors = ["Admin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]